sudo: required
dist: bionic
language: cpp
os: linux
compiler: g++
install:
- sudo apt-get install gcc-4.8
- sudo apt-get install g++-4.8
script: 
- export CC=gcc-4.8
- export CC_FOR_BUILD=gcc-4.8
- export CXX=g++-4.8
- export CXX_FOR_BUILD=g++-4.8
- cd client/c
- ./bootstrap.sh
- ./configure
- make
- cd ~/
- ./travis-script/test_c_client.sh
