sudo: required
dist: bionic
language: cpp
os: linux
compiler: g++
install:
- sudo apt-get install gcc-4.8
- sudo apt-get install g++-4.8
script: 
- cd client/c
- ./bootstrap.sh
- ./configure
- make
- ./travis-script/test_c_client.sh
